// Lifts the three design-system <style> blocks out of servicemind-design-system.html
// into servicemind.css, so new pages can link one stylesheet instead of copying
// CSS around. Block 4 is the documentation chrome and is deliberately dropped.
import { readFileSync, writeFileSync } from 'node:fs';

const html = readFileSync('servicemind-design-system.html', 'utf8');
const blocks = [...html.matchAll(/<style>([\s\S]*?)<\/style>/g)].map((m) => m[1]);

if (blocks.length !== 4) throw new Error(`expected 4 style blocks, found ${blocks.length}`);
if (!/DOCUMENTATION CHROME/.test(blocks[3])) throw new Error('block 4 is not the doc chrome — check the order');

const css = `/* ServiceMind design system — tokens, Material substrate and the verbatim
   .tis-* extraction. Generated by build-css.mjs from servicemind-design-system.html;
   edit that file, not this one. Pair it with the font <link>s the app uses. */
${blocks.slice(0, 3).join('\n').trim()}
`;

writeFileSync('servicemind.css', css);
console.log(`servicemind.css  ${(css.length / 1024).toFixed(0)} KB from ${blocks.length - 1} blocks`);
